# Helium

hide_ascii      = false
spacing         = 2
padding         = 0
separator       = "->"
key_color       = "Red"
separator_color = "Yellow"

[palette]
type            = "Full"
glyph           = "ɑ "
visible         = true

[bar]
glyph           = "●"
symbol_open     = "("
symbol_close    = ")"
hide_delimiters = false
visible         = true

[box]
title           = " alpha "
border          = "rounded"
visible         = true

[box.inner_margin]
x               = 2
y               = 1

[randomize]
key_color       = false
separator_color = false
pool            = "hexadecimal"

[keys]
host            = "Host"
kernel          = "Kernel"
battery         = "Battery"
os              = "OS"
de              = "DE"
wm              = "WM"
distro          = "Distro"
terminal        = "Terminal"
shell           = "Shell"
packages        = "Packages"
uptime          = "Uptime"
memory          = "Memory"
machine         = "Machine"
local_ip        = "IP"
backlight       = "Brightness"
resolution      = "Resolution"
cpu_load        = "CPU Load"
cpu             = "CPU"
